version: build-{build}

environment:
  global:
    PLATFORMTOOLSET: "v140"
    CMAKEPREFIXPATH: "."
    SEVENZIP: "C:\\Program Files\\7-Zip\\7z.exe"
    WGET_BIN: "C:\\msys64\\usr\\bin\\wget.exe"
    APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
  matrix:
    - BUILD_TYPE: MinSizeRel
      COMPILER: MinGW-w32
      COMPILER_FAMILY: MinGW
      GENERATOR: "MinGW Makefiles"
      PLATFORM: Win32
      CMAKEPREFIXPATH: "C:/Qt/Tools/mingw730_32"
      TOOLCHAIN_BIN: "C:\\Qt\\Tools\\mingw730_32\\bin"
    - BUILD_TYPE: MinSizeRel
      COMPILER: MinGW-w64
      COMPILER_FAMILY: MinGW
      GENERATOR: "MinGW Makefiles"
      PLATFORM: x64
      CMAKEPREFIXPATH: "C:/Qt/Tools/mingw730_64"
      TOOLCHAIN_BIN: "C:\\Qt\\Tools\\mingw730_64\\bin"

build_script:
  - git submodule init
  - git submodule update
  - md b
  - cd b
  - if NOT [%TOOLCHAIN_BIN%]==[] set PATH=%TOOLCHAIN_BIN%;%PATH:C:\Program Files\Git\usr\bin;=%
  - cmake -G "%GENERATOR%" -DCPACK_PACKAGE_FILE_NAME=thextech-%APPVEYOR_REPO_BRANCH%-%COMPILER%-%BUILD_TYPE%-%PLATFORM% -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DCMAKE_PREFIX_PATH=%CMAKEPREFIXPATH% ..
  - cmake --build . --config %BUILD_TYPE% -- -j 2
  - cpack ..
  - appveyor PushArtifact "thextech-%APPVEYOR_REPO_BRANCH%-%COMPILER%-%BUILD_TYPE%-%PLATFORM%.7z"

deploy:
  - provider: Environment
    name: WohlnetFTP

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

