version: 1.0.{build}

environment:
  matrix:
#    - BUILD_TYPE: Debug
#      COMPILER: MinGW
#      GENERATOR: "MinGW Makefiles"
#      PLATFORM: Win32
#    - BUILD_TYPE: Release
#      COMPILER: MinGW
#      GENERATOR: "MinGW Makefiles"
#      PLATFORM: Win32
    - BUILD_TYPE: Debug
      COMPILER: MinGW-w32
      GENERATOR: "MinGW Makefiles"
      PLATFORM: Win32
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2019"
    - BUILD_TYPE: Release
      COMPILER: MinGW-w32
      GENERATOR: "MinGW Makefiles"
      PLATFORM: Win32
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2019"
    - BUILD_TYPE: Debug
      COMPILER: MinGW-w64
      GENERATOR: "MinGW Makefiles"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2019"
      PLATFORM: x64
    - BUILD_TYPE: Release
      COMPILER: MinGW-w64
      GENERATOR: "MinGW Makefiles"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2019"
      PLATFORM: x64
    - BUILD_TYPE: Debug
      COMPILER: MSVC15
      GENERATOR: "Visual Studio 14 2015 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
      PLATFORM: x64
      PLATFORMTOOLSET: "v140_xp"
    - BUILD_TYPE: Release
      COMPILER: MSVC15
      GENERATOR: "Visual Studio 14 2015 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
      PLATFORM: x64
      PLATFORMTOOLSET: "v140_xp"
    - BUILD_TYPE: Debug
      COMPILER: MSVC15
      GENERATOR: "Visual Studio 14 2015"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
      PLATFORM: Win32
      PLATFORMTOOLSET: "v140_xp"
    - BUILD_TYPE: Release
      COMPILER: MSVC15
      GENERATOR: "Visual Studio 14 2015"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
      PLATFORM: Win32
      PLATFORMTOOLSET: "v140_xp"
    - BUILD_TYPE: Debug
      COMPILER: MSVC17
      GENERATOR: "Visual Studio 15 2017 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
      PLATFORM: x64
      PLATFORMTOOLSET: "v141_xp"
    - BUILD_TYPE: Release
      COMPILER: MSVC17
      GENERATOR: "Visual Studio 15 2017 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
      PLATFORM: x64
      PLATFORMTOOLSET: "v141_xp"
    - BUILD_TYPE: Debug
      COMPILER: MSVC17
      GENERATOR: "Visual Studio 15 2017"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
      PLATFORM: Win32
      PLATFORMTOOLSET: "v141_xp"
    - BUILD_TYPE: Release
      COMPILER: MSVC17
      GENERATOR: "Visual Studio 15 2017"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
      PLATFORM: Win32
      PLATFORMTOOLSET: "v141_xp"
    - BUILD_TYPE: Debug
      COMPILER: MSVC19
      GENERATOR: "Visual Studio 16 2019"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2019"
      PLATFORM: Win32
      PLATFORMTOOLSET: "v142"
    - BUILD_TYPE: Release
      COMPILER: MSVC19
      GENERATOR: "Visual Studio 16 2019"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2019"
      PLATFORM: Win32
      PLATFORMTOOLSET: "v142"
    - BUILD_TYPE: Debug
      COMPILER: MSVC19
      GENERATOR: "Visual Studio 16 2019"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2019"
      PLATFORM: x64
      PLATFORMTOOLSET: "v142"
    - BUILD_TYPE: Release
      COMPILER: MSVC19
      GENERATOR: "Visual Studio 16 2019"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2019"
      PLATFORM: x64
      PLATFORMTOOLSET: "v142"

install:
  - appveyor DownloadFile https://github.com/yasm/yasm/releases/download/v1.3.0/yasm-1.3.0-win64.exe -FileName yasm.exe
  - set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%

build_script:
  - md build-%COMPILER%-%BUILD_TYPE%-%PLATFORM%
  - cd build-%COMPILER%-%BUILD_TYPE%-%PLATFORM%
  - if [%COMPILER%]==[MinGW] set PATH=C:\MinGW\bin;%PATH:C:\Program Files\Git\usr\bin;=%
  - if [%COMPILER%]==[MinGW-w32] set PATH=C:\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32\bin;%PATH:C:\Program Files\Git\usr\bin;=%
  - if [%COMPILER%]==[MinGW-w64] set PATH=C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;%PATH:C:\Program Files\Git\usr\bin;=%
  - cmake -G "%GENERATOR%" -DUSE_LOCAL_SDL2=ON -DSDL2_GIT_BRANCH=SDL2 -DCMAKE_INSTALL_PREFIX=AudioCodecs ..
  - if [%COMPILER%]==[MinGW] cmake --build . --config %BUILD_TYPE% -- -j 2
  - if [%COMPILER%]==[MinGW] mingw32-make install
  - if [%COMPILER%]==[MinGW-w32] cmake --build . --config %BUILD_TYPE% -- -j 2
  - if [%COMPILER%]==[MinGW-w32] mingw32-make install
  - if [%COMPILER%]==[MinGW-w64] cmake --build . --config %BUILD_TYPE% -- -j 2
  - if [%COMPILER%]==[MinGW-w64] mingw32-make install
  - if [%COMPILER%]==[MSVC15] cmake --build . --config %BUILD_TYPE% --target install
  - if [%COMPILER%]==[MSVC17] cmake --build . --config %BUILD_TYPE% --target install
  - if [%COMPILER%]==[MSVC19] cmake --build . --config %BUILD_TYPE% --target install
  - 7z a -t7z -mx9 "AudioCodecs-%COMPILER%-%BUILD_TYPE%-%PLATFORM%.7z" "AudioCodecs"
  - move AudioCodecs-%COMPILER%-%BUILD_TYPE%-%PLATFORM%.7z ..

artifacts:
  - path: 'AudioCodecs-$(COMPILER)-$(BUILD_TYPE)-$(PLATFORM).7z'

deploy:
  - provider: Environment
    name: WohlnetFTP

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
