language: cpp

os:
    - linux
    - osx

env:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

dist: trusty

git:
    depth: 3

branches:
    only:
    - master

addons:
    apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['ninja-build']

install:
    - mkdir build; cd build
    - if [ $TRAVIS_OS_NAME == linux ]; then cmake -G "Ninja" -DDOWNLOAD_SDL2_DEPENDENCY=ON -DCMAKE_INSTALL_PREFIX=~/AudioCodecs/ -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..; fi
    - if [ $TRAVIS_OS_NAME == osx ];   then cmake -G "Xcode" -DDOWNLOAD_SDL2_DEPENDENCY=ON -DCMAKE_INSTALL_PREFIX=~/AudioCodecs/ -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..; fi

script:
    - cmake --build . --config ${BUILD_TYPE} --target install -- -j 2

